ALTER TABLE "question"
  ADD COLUMN IF NOT EXISTS "expected_tc" TEXT,
  ADD COLUMN IF NOT EXISTS "expected_sc" TEXT;

ALTER TABLE "test_case"
  ADD COLUMN IF NOT EXISTS "input" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "output" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "is_hidden" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "hint"
  ADD COLUMN IF NOT EXISTS "content" TEXT;
